apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 9000 # ClusterIPで受け付けるPort番号
      targetPort: 9000 # 転送先のコンテナのPort番号
    - name: "http-console-page-port"
      protocol: "TCP"
      port: 9090 # ClusterIPで受け付けるPort番号
      targetPort: 9090 # 転送先のコンテナのPort番号
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minio
  name: minio
spec:
  replicas: 1
  selector: # StatefulSetによって対象となるPodのラベルを指定する。
    matchLabels:
      app: minio # Podのlabelsに指定したラベルを記述する。
  serviceName: minio
  template: # Podのテンプレート
    metadata: # デプロイするPodのメタデータ
      labels:
        app: minio # Podのラベル名
    spec: # デプロイするPodの詳細な情報を記述する。
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          env:
            - name: MINIO_ROOT_USER # ROOTユーザー名
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD # ROOTパスワード
              value: minioadmin
          resources:
            limits: # Podが利用可能な上限値
              memory: 512Mi
              cpu: "1"
            requests: # Podが要求する下限値
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - name: localvolume
              mountPath: /data
      volumes:
        - name: localvolume
          persistentVolumeClaim:
            claimName: dynamic-provisioning-claim
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-provisioning-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # MinIOに割り当てるストレージサイズ
